### ISSUE TITLE
Last played game glitching

### ISSUE THREAD

**Issue by pycoder08** [saVantCZ/XBOXreborn#4]
I'm new to playnite, but I have a few questions

1. how do I edit the extension file to add my username/color theme?

2. On the homepage of the fullscreen menu, my last played game glitches out and looks like the attatched photo 
<img width="1913" alt="Screenshot 2023-03-01 173535" src="https://user-images.githubusercontent.com/126736146/222308213-0146b76b-7ac2-4024-b745-11875038d4a5.png">

3. Using 'b' on an xbox controller doesn't exit menus, not sure if it's intended to

4. can I edit the code of this theme to add custom sounds/edit the UI? I'd like to fiddle around with it but I'm not sure how

Overall very impressive, it's the only xbox theme that supports playnite version 10

**Comment by saVantCZ** [comment]
You have wrong cover sizes, use only 1:1 size... Everything else is edit-able in constants.xaml file Inside theme folder

**Comment by pycoder08** [comment]
I selected 1:1 ratio under the 'grid view' menu in playnite. 
<img width="641" alt="image" src="https://user-images.githubusercontent.com/126736146/222481467-d47211c1-3683-46b8-8c15-ba2ada01d161.png">

I uninstalled and reinstalled the theme to try to fix these issues, but now under general -> theme the only item on the drop-down is "default" despite xboxreborn being present in the "themes" folder on my PC
<img width="641" alt="image" src="https://user-images.githubusercontent.com/126736146/222481565-3b40de5c-7158-4568-b85a-44facd3f0fbf.png">

**Comment by saVantCZ** [comment]
Please set all required settings written in readme file on github

Columns: 7
Rows: 3

In Fullscreen settings.

Theme folder is located in Playnite install location (default %appdata%) there locate Theme folder, Xbox reborn folder and edit constants.xaml file in notepad... You can follow everything on my main GitHub page.

**Comment by pycoder08** [comment]
I realized now that playnite has to be in fullscreen mode to access these settings. Thank you for your help.

**Comment by pycoder08** [comment]
One more question: There doesn't seem to be a settings menu in this theme, how can I access the fullscreen settings to change themes/edit settings?

**Comment by saVantCZ** [comment]
On controller, menu button.

**Comment by pycoder08** [comment]
Thanks for your help, this has been useful.
