### ISSUE TITLE
Cant open Playnite menu (or whatever it's called)

### ISSUE THREAD

**Issue by Caddy8970** [saVantCZ/XBOXreborn#5]
Im talking about this:
![Guide](https://user-images.githubusercontent.com/113631055/232223421-7c4858b0-1502-4a45-8513-6954162d7aa2.jpg)
I can't understand how to open it. Clicking on the avatar doesn't work

**Comment by saVantCZ** [comment]
Theme is meant to be used with controller only, no mouse support.

**Comment by Caddy8970** [comment]
Im using a controller

**Comment by saVantCZ** [comment]
Then just press menu button on controller.

**Comment by Caddy8970** [comment]
oh
