### ISSUE TITLE
features

### ISSUE THREAD

**Issue by Koriebonx98** [saVantCZ/XBOXreborn#7]
can you please do it so it supports the addon success story!!

also any chance you can change the menu gui to the one like "xboxseriesish"  as it fells outdated and not in suit with the theme 
and optiion for "Playstate" as well would be good where we can resume games in fullsreen mode like on the new xbox ones

**Comment by saVantCZ** [comment]
Which menu GUI you have in mind? Could you share screenshot?

**Comment by Koriebonx98** [comment]
When using the other Xbox serieeish theme the main menu button in fullscreen mode to minimise, restart system ect

**Comment by saVantCZ** [comment]
My menu simulate actual Guide menu from Xbox. Menu in xboxseriesish is default just different colors.

https://github.com/saVantCZ/XBOXreborn/blob/main/Media/Guide.jpg


https://www.consolegames.ro/forum/attachments/f122-microsoft-xbox-series/291772d1606771338-xbox-dashboard-xbox-preview-xbox-insider-xbox-com-dark_guide_gameactivity.jpg

**Comment by Koriebonx98** [comment]
I’ll try again tonight I’ll even reinstall just incase, as there’s 4 diffrent Xbox themes. There was one that was perfect but lacked menu, one lacked achievements and the other 2 with the return to menu it seems clunky. I’ll double check later and let you know
